const dictionaries = {
  logType: { CIVIL: "土建", DECORATION: "精装" },
  constructionStatus: { DRAFT: "草稿", SUBMITTED: "已提交", LOCKED: "已锁定" },
  inspectionStatus: {
    DRAFT: "草稿",
    SUBMITTED: "已提交",
    PENDING_SIGNATURE: "待签字",
    PENDING_RECTIFICATION: "待整改",
    PENDING_REINSPECTION: "待复验",
    PASSED: "已通过",
    FAILED: "未通过",
    VOID: "已作废",
  },
  conclusion: {
    PASSED: "通过",
    RECTIFICATION_REQUIRED: "整改后复验",
    FAILED: "不通过",
  },
  sourceType: {
    MANUAL: "手动创建",
    DAILY_LOG: "施工日志",
    INSPECTION: "验收发现",
    OWNER_FEEDBACK: "业主反馈",
    AFTER_SALES: "售后报修",
  },
  issueType: {
    QUALITY: "质量问题",
    PROGRESS: "进度问题",
    SAFETY: "安全问题",
    MATERIAL: "材料问题",
    DESIGN: "设计问题",
    SERVICE: "服务问题",
    OTHER: "其他问题",
  },
  severity: { LOW: "一般", MEDIUM: "中等", HIGH: "严重", CRITICAL: "紧急" },
  issueStatus: {
    OPEN: "待分配",
    ASSIGNED: "已分配",
    RECTIFYING: "整改中",
    PENDING_REVIEW: "待复验",
    REJECTED: "复验不通过",
    CLOSED: "已关闭",
    CANCELLED: "已取消",
  },
  paymentStatus: {
    0: "草稿",
    1: "审批中",
    2: "已撤销",
    3: "已通过",
    4: "已驳回",
  },
  handoverType: {
    DESIGN_TO_CIVIL: "设计交接土建",
    DESIGN_TO_DECORATION: "设计交接精装",
    CIVIL_TO_DECORATION: "土建交接精装",
    OTHER: "其他交接",
  },
  flowType: { DESIGN: "设计", CIVIL: "土建", DECORATION: "精装" },
  handoverConclusion: {
    ACCEPTED: "接收通过",
    CONDITIONAL_ACCEPTANCE: "有条件接收",
    REJECTED: "拒绝接收",
  },
  handoverStatus: {
    DRAFT: "草稿",
    PENDING_HANDOVER: "待移交",
    PENDING_RECEIVE: "待接收",
    REJECTED: "已退回",
    COMPLETED: "已完成",
    CANCELLED: "已取消",
  },
};

const options = (name) =>
  Object.keys(dictionaries[name]).map((value) => ({
    value,
    label: dictionaries[name][value],
  }));
const field = (prop, label, extra = {}) => ({ prop, label, ...extra });

export const documentConfigs = {
  constructionLog: {
    title: "施工日志",
    api: "constructionLog",
    detailPath: "/constructionLogDetail",
    filters: [
      field("projectName", "项目名称"),
      field("logType", "日志类型", {
        type: "select",
        options: options("logType"),
      }),
      field("status", "状态", {
        type: "select",
        options: options("constructionStatus"),
      }),
      field("dateRange", "日志日期", { type: "daterange" }),
    ],
    columns: [
      field("projectName", "项目名称", { minWidth: 160 }),
      field("stageName", "项目阶段", { minWidth: 120 }),
      field("logDate", "日志日期", { width: 120 }),
      field("logType", "日志类型", { width: 100, dict: "logType" }),
      field("filledByName", "填写人", { width: 110 }),
      field("weather", "天气", { width: 100 }),
      field("status", "状态", { width: 100, dict: "constructionStatus" }),
    ],
    fields: [
      field("projectName", "项目名称"),
      field("stageName", "项目阶段"),
      field("logDate", "日志日期"),
      field("logType", "日志类型", { dict: "logType" }),
      field("filledByName", "填写人"),
      field("status", "状态", { dict: "constructionStatus" }),
      field("weather", "天气"),
      field("temperature", "温度"),
      field("currentProgressSummary", "今日施工进展", { span: 2 }),
      field("tradeProgress", "各工种进展", { type: "json", span: 2 }),
      field("expectedNodeCompletionAt", "预计节点完成时间"),
      field("hasIssue", "存在现场问题", { type: "boolean" }),
      field("siteIssues", "现场问题", { type: "json", span: 2 }),
      field("nextDayPlan", "下一步工作计划", { span: 2 }),
      field("nextDayTradePlan", "明日工种安排", { type: "json", span: 2 }),
      field("ownerMentions", "业主配合事项", { type: "json", span: 2 }),
      field("qcMentions", "质检事项", { type: "json", span: 2 }),
      field("remark", "备注", { span: 2 }),
      field("submittedAt", "提交时间"),
      field("lockedAt", "锁定时间"),
      field("createdAt", "创建时间"),
      field("updatedAt", "更新时间"),
    ],
  },
  inspection: {
    title: "验收单",
    api: "inspection",
    detailPath: "/inspectionDetail",
    filters: [
      field("projectName", "项目名称"),
      field("inspectionName", "验收名称"),
      field("status", "状态", {
        type: "select",
        options: options("inspectionStatus"),
      }),
      field("dateRange", "验收日期", { type: "daterange" }),
    ],
    columns: [
      field("inspectionName", "验收名称", { minWidth: 170 }),
      field("projectName", "项目名称", { minWidth: 160 }),
      field("stageName", "项目阶段", { width: 130 }),
      field("inspectionDate", "验收日期", { width: 120 }),
      field("inspectionRound", "轮次", { width: 80 }),
      field("qcUserName", "质检员", { width: 100 }),
      field("conclusion", "结论", { width: 120, dict: "conclusion" }),
      field("status", "状态", { width: 120, dict: "inspectionStatus" }),
    ],
    fields: [
      field("inspectionName", "验收名称"),
      field("projectName", "项目名称"),
      field("stageName", "项目阶段"),
      field("inspectionRound", "验收轮次"),
      field("inspectionDate", "验收日期"),
      field("status", "状态", { dict: "inspectionStatus" }),
      field("inspectionStartedAt", "开始时间"),
      field("inspectionFinishedAt", "结束时间"),
      field("qcUserName", "质检员"),
      field("projectManagerUserName", "项目经理"),
      field("participants", "参与人员", { type: "json", span: 2 }),
      field("checkItems", "验收检查项", { type: "json", span: 2 }),
      field("sitePhotos", "现场照片", { type: "json", span: 2 }),
      field("conclusion", "验收结论", { dict: "conclusion" }),
      field("rectificationDeadline", "整改截止时间"),
      field("issueCount", "问题总数"),
      field("openIssueCount", "未关闭问题数"),
      field("issueTicketIds", "关联问题单", { type: "json", span: 2 }),
      field("signatures", "签字信息", { type: "json", span: 2 }),
      field("remark", "备注", { span: 2 }),
      field("passedAt", "通过时间"),
      field("createdAt", "创建时间"),
    ],
  },
  issueTicket: {
    title: "问题单",
    api: "issueTicket",
    detailPath: "/issueTicketDetail",
    filters: [
      field("projectName", "项目名称"),
      field("keyword", "编号/标题"),
      field("issueType", "问题类型", {
        type: "select",
        options: options("issueType"),
      }),
      field("severity", "严重程度", {
        type: "select",
        options: options("severity"),
      }),
      field("status", "状态", {
        type: "select",
        options: options("issueStatus"),
      }),
    ],
    columns: [
      field("code", "问题编号", { width: 140 }),
      field("title", "问题标题", { minWidth: 180 }),
      field("projectName", "项目名称", { minWidth: 150 }),
      field("issueType", "问题类型", { width: 110, dict: "issueType" }),
      field("severity", "严重程度", { width: 100, dict: "severity" }),
      field("responsibleUserName", "责任人", { width: 100 }),
      field("rectificationDeadline", "整改截止时间", { width: 160 }),
      field("status", "状态", { width: 110, dict: "issueStatus" }),
    ],
    fields: [
      field("code", "问题编号"),
      field("title", "问题标题"),
      field("projectName", "项目名称"),
      field("stageName", "项目阶段"),
      field("sourceType", "问题来源", { dict: "sourceType" }),
      field("issueType", "问题类型", { dict: "issueType" }),
      field("severity", "严重程度", { dict: "severity" }),
      field("status", "状态", { dict: "issueStatus" }),
      field("description", "问题描述", { span: 2 }),
      field("issuePhotos", "问题现场照片", { type: "json", span: 2 }),
      field("reportedByName", "发现人"),
      field("reportedAt", "发现时间"),
      field("responsibleUserName", "整改责任人"),
      field("rectificationDeadline", "整改截止时间"),
      field("rectificationCount", "整改次数"),
      field("rectificationSubmittedAt", "整改提交时间"),
      field("rectificationDescription", "整改说明", { span: 2 }),
      field("rectificationPhotos", "整改照片", { type: "json", span: 2 }),
      field("reviewUserName", "复验人"),
      field("reviewResult", "复验结果", { dict: "conclusion" }),
      field("reviewRemark", "复验说明", { span: 2 }),
      field("reviewPhotos", "复验照片", { type: "json", span: 2 }),
      field("closedAt", "关闭时间"),
      field("cancelReason", "取消原因"),
      field("remark", "备注", { span: 2 }),
      field("createdAt", "创建时间"),
    ],
  },
  paymentRequest: {
    title: "请款单",
    api: "paymentRequest",
    detailPath: "/paymentRequestDetail",
    filters: [
      field("projectName", "项目名称"),
      field("applicantName", "申请人"),
      field("status", "状态", {
        type: "select",
        options: options("paymentStatus"),
      }),
    ],
    columns: [
      field("projectName", "项目名称", { minWidth: 180 }),
      field("applicantName", "申请人", { width: 120 }),
      field("amount", "请款金额", { width: 140, type: "money" }),
      field("description", "请款说明", { minWidth: 220 }),
      field("status", "状态", { width: 100, dict: "paymentStatus" }),
      field("submitTime", "提交时间", { width: 160 }),
      field("createdAt", "创建时间", { width: 160 }),
    ],
    fields: [
      field("projectName", "项目名称"),
      field("applicantName", "申请人"),
      field("amount", "请款金额", { type: "money" }),
      field("status", "状态", { dict: "paymentStatus" }),
      field("description", "请款说明", { span: 2 }),
      field("attachments", "附件", { type: "json", span: 2 }),
      field("submitTime", "提交时间"),
      field("createdByName", "创建人"),
      field("createdAt", "创建时间"),
      field("updatedAt", "更新时间"),
    ],
  },
  materialArrival: {
    title: "材料到场",
    api: "materialArrival",
    detailPath: "/materialArrivalDetail",
    filters: [
      field("projectName", "项目名称"),
      field("dateRange", "到场时间", { type: "daterange" }),
    ],
    columns: [
      field("projectName", "项目名称", { minWidth: 200 }),
      field("arrivalAt", "到场时间", { width: 180 }),
      field("createdByName", "登记人", { width: 120 }),
      field("createdAt", "登记时间", { width: 180 }),
    ],
    fields: [
      field("projectName", "项目名称"),
      field("projectCode", "项目编号"),
      field("arrivalAt", "到场时间"),
      field("createdByName", "登记人"),
      field("files", "相关附件", { type: "json", span: 2 }),
      field("createdAt", "登记时间"),
      field("updatedAt", "更新时间"),
    ],
  },
  projectHandover: {
    title: "交接单",
    api: "projectHandover",
    detailPath: "/projectHandoverDetail",
    filters: [
      field("projectName", "项目名称"),
      field("keyword", "编号/名称"),
      field("handoverType", "交接类型", {
        type: "select",
        options: options("handoverType"),
      }),
      field("status", "状态", {
        type: "select",
        options: options("handoverStatus"),
      }),
    ],
    columns: [
      field("handoverCode", "交接单编号", { width: 150 }),
      field("handoverName", "交接单名称", { minWidth: 180 }),
      field("projectName", "项目名称", { minWidth: 160 }),
      field("handoverType", "交接类型", { width: 150, dict: "handoverType" }),
      field("handoverUserName", "移交负责人", { width: 110 }),
      field("receiverUserName", "接收负责人", { width: 110 }),
      field("handoverDate", "交接日期", { width: 120 }),
      field("status", "状态", { width: 100, dict: "handoverStatus" }),
    ],
    fields: [
      field("handoverCode", "交接单编号"),
      field("handoverName", "交接单名称"),
      field("projectName", "项目名称"),
      field("handoverType", "交接类型", { dict: "handoverType" }),
      field("fromStageName", "移交阶段"),
      field("toStageName", "接收阶段"),
      field("fromFlowType", "移交流程", { dict: "flowType" }),
      field("toFlowType", "接收流程", { dict: "flowType" }),
      field("handoverDate", "交接日期"),
      field("status", "状态", { dict: "handoverStatus" }),
      field("handoverUserName", "移交负责人"),
      field("receiverUserName", "接收负责人"),
      field("handoverItems", "交接检查项", { type: "json", span: 2 }),
      field("documentFiles", "移交资料", { type: "json", span: 2 }),
      field("unfinishedItems", "遗留事项", { type: "json", span: 2 }),
      field("openIssueCount", "未关闭问题数"),
      field("handoverConclusion", "交接结论", { dict: "handoverConclusion" }),
      field("handoverRemark", "移交方说明", { span: 2 }),
      field("receiverRemark", "接收方意见", { span: 2 }),
      field("handoverSignedAt", "移交方签字时间"),
      field("receiverSignedAt", "接收方签字时间"),
      field("completedAt", "完成时间"),
      field("cancelReason", "取消原因"),
      field("createdAt", "创建时间"),
      field("updatedAt", "更新时间"),
    ],
  },
};

export function displayValue(value, definition) {
  if (value === null || value === undefined || value === "") return "-";
  if (definition.dict) return dictionaries[definition.dict][value] || value;
  if (definition.type === "boolean") return Number(value) === 1 ? "是" : "否";
  if (definition.type === "money")
    return (
      "¥" +
      Number(value).toLocaleString("zh-CN", {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
      })
    );
  return value;
}
